# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      opentelemetry:
        patterns:
          - "*opentelemetry*"
        update-types:
          - "major"
          - "minor"
      rust-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: uv
    directory: "/tapo-py"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      python-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      github-actions-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
