from __future__ import annotations
from typing import AsyncIterable, AsyncIterator, Iterable, Iterator

from .discovery_raw_result import MaybeDiscoveryRawResult

class DeviceDiscoveryRawIter(
    Iterator[MaybeDiscoveryRawResult], AsyncIterator[MaybeDiscoveryRawResult]
):
    def __iter__(self) -> DeviceDiscoveryRawIter: ...
    def __aiter__(self) -> DeviceDiscoveryRawIter: ...
    def __next__(self) -> MaybeDiscoveryRawResult: ...
    async def __anext__(self) -> MaybeDiscoveryRawResult: ...

class DeviceDiscoveryRaw(Iterable[MaybeDiscoveryRawResult], AsyncIterable[MaybeDiscoveryRawResult]):
    def __iter__(self) -> DeviceDiscoveryRawIter: ...
    def __aiter__(self) -> DeviceDiscoveryRawIter: ...
