from typing import Final, Tuple

class Color:
    """List of preset colors as defined in the Google Home app."""

    CoolWhite: Final[Color]
    Daylight: Final[Color]
    Ivory: Final[Color]
    WarmWhite: Final[Color]
    Incandescent: Final[Color]
    Candlelight: Final[Color]
    Snow: Final[Color]
    GhostWhite: Final[Color]
    AliceBlue: Final[Color]
    LightGoldenrod: Final[Color]
    LemonChiffon: Final[Color]
    AntiqueWhite: Final[Color]
    Gold: Final[Color]
    Peru: Final[Color]
    Chocolate: Final[Color]
    SandyBrown: Final[Color]
    Coral: Final[Color]
    Pumpkin: Final[Color]
    Tomato: Final[Color]
    Vermilion: Final[Color]
    OrangeRed: Final[Color]
    Pink: Final[Color]
    Crimson: Final[Color]
    DarkRed: Final[Color]
    HotPink: Final[Color]
    Smitten: Final[Color]
    MediumPurple: Final[Color]
    BlueViolet: Final[Color]
    Indigo: Final[Color]
    LightSkyBlue: Final[Color]
    CornflowerBlue: Final[Color]
    Ultramarine: Final[Color]
    DeepSkyBlue: Final[Color]
    Azure: Final[Color]
    NavyBlue: Final[Color]
    LightTurquoise: Final[Color]
    Aquamarine: Final[Color]
    Turquoise: Final[Color]
    LightGreen: Final[Color]
    Lime: Final[Color]
    ForestGreen: Final[Color]

    def get_color_config(self) -> Tuple[int, int, int]:
        """Get the `hue`, `saturation`, and `color_temperature` of the color."""
