name: "Tapo Rust"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rust-checks:
    uses: ./.github/workflows/tapo-rs-checks.yml
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
    needs: [rust-checks]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: dtolnay/rust-toolchain@stable
      - name: Run cargo login
        run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Run build
        run: cargo build --package tapo --release --verbose
      - name: Run cargo publish
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: cargo publish --package tapo
